#!/bin/bash

if [ -z $1 ]
then
	if pgrep -f "cassandra" > /dev/null 2>&1
	then
		echo "UP: Cassandra, nyan admin bot"
	else
		echo "DOWN: Cassandra, nyan admin bot"
	fi
	if pgrep -f "patchy" > /dev/null 2>&1
	then
		echo "UP: Patchouli, old python image search"
	else
		echo "DOWN: Patchouli, old python image search"
	fi
	if pgrep -f "megumin" > /dev/null 2>&1
	then
		echo "UP: Megumin, selfbot services"
	else
		echo "DOWN: Megumin, selfbot services"
	fi
	if pgrep -f "qasi" > /dev/null 2>&1
	then
		echo "UP: QASI, cassandra rewrite"
	else
		echo "DOWN: QASI, cassandra rewrite"
	fi
	echo "Mikachu is connected via IRC."
else
	if [ $1 = "cassie" ]
	then
		name="cassandra"
		out="hi :D"
	elif [ $1 = "patchy" ]
	then
		name="patchy"
		out="lipgloss."
	elif [ $1 = "megumin" ]
	then
		name="megumin"
		out="I dont know anything about this character"
	elif [ $1 = "qasi" ]
	then
		name="qasi"
		out="hey :)"
	fi
	
	if pgrep -f $name > /dev/null 2>&1
	then
	  echo "$1: $out"
	else
	  echo "$1 isn't here right now."
	fi
fi
exit 0
